server:
  port: 8081
# 设置日志的路径，在logback-spring.xml中引用了此属性作为日志文件路径
logging:
  file:
    path: /logs/diditech-iov-gps-test-api
  config: classpath:logback-spring.xml
# 指定logfile端点的日志位置，有以下两个用途
# 1.使用actuator的logfile端点访问到日志文件
# 2.使用spring-boot-admin-server访问到服务的logfile端点，在监控中心查看服务日志
endpoints:
  logfile: ${logging.file.path}/total.log

datasource:
  common:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 5
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  default:
    url: jdbc:mysql://124.129.247.23:14408/dd_new?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 112233

spring:
  data:
    mongodb:
      #      uri: mongodb://p_2009_ddmonitor:QXgjDpnu3f^j@114.215.85.26:37037/geo
      uri: mongodb://p_1709_ddmonitor:ddmqw$wc39pQM@192.168.1.199:37017/green_area

