server:
  port: 8081
# 设置日志的路径，在logback-spring.xml中引用了此属性作为日志文件路径
logging:
  file:
    path: /logs/demo
  config: classpath:logback-spring.xml
# 指定logfile端点的日志位置，有以下两个用途
# 1.使用actuator的logfile端点访问到日志文件
# 2.使用spring-boot-admin-server访问到服务的logfile端点，在监控中心查看服务日志
endpoints:
  logfile: ${logging.file.path}/total.log

